from __future__ import annotations

from typing import Any

from app.utils.helpers import estimate_drive_minutes, geodesic_distance_km


class MockMapsProvider:
    provider_name = "mock"

    async def geocode_location(self, query: str) -> dict[str, Any]:
        seed = sum(ord(char) for char in query)
        latitude = round(10 + (seed % 800) / 100, 4)
        longitude = round(70 + (seed % 900) / 100, 4)
        return {"query": query, "latitude": latitude, "longitude": longitude, "formatted_address": query}

    async def search_nearby_places(self, destination: str, category: str) -> list[dict[str, Any]]:
        base = await self.geocode_location(destination)
        return [
            {
                "name": f"{destination} {category.title()} Spot {index + 1}",
                "category": category,
                "address": f"{category.title()} Area {index + 1}, {destination}",
                "latitude": round(base["latitude"] + index * 0.03, 4),
                "longitude": round(base["longitude"] + index * 0.02, 4),
                "rating": 4.1 + (index * 0.1),
                "review_count": 100 + index * 25,
                "estimated_visit_hours": 2.0 if category != "food" else 1.5,
                "place_id": f"mock-{destination.lower()}-{category}-{index + 1}",
                "source": "mock_maps",
            }
            for index in range(4)
        ]

    async def compute_route_matrix(
        self,
        origins: list[dict[str, Any]],
        destinations: list[dict[str, Any]],
        travel_mode: str = "DRIVE",
    ) -> list[dict[str, Any]]:
        legs: list[dict[str, Any]] = []
        for origin in origins:
            for destination in destinations:
                distance = geodesic_distance_km(
                    origin["latitude"],
                    origin["longitude"],
                    destination["latitude"],
                    destination["longitude"],
                )
                legs.append(
                    {
                        "origin_name": origin["name"],
                        "destination_name": destination["name"],
                        "travel_mode": travel_mode,
                        "distance_km": distance,
                        "duration_minutes": estimate_drive_minutes(distance),
                        "provider": "mock",
                    }
                )
        return legs

    async def get_place_details(self, place_id: str) -> dict[str, Any]:
        return {
            "place_id": place_id,
            "description": f"Details for {place_id} generated by mock provider.",
            "opening_hours": ["09:00-18:00"],
            "website": None,
        }
